# Generated by Django 5.1.1 on 2024-11-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='genero',
            field=models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'femenino'), ('', ''), ('user', 'user')], default='', max_length=10),
        ),
    ]
