# Generated by Django 5.1.1 on 2024-10-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ajustes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size_small', models.CharField(max_length=10)),
                ('font_size_medium', models.CharField(max_length=10)),
                ('font_size_large', models.CharField(max_length=10)),
                ('color_primary', models.CharField(max_length=7)),
                ('color_secondary', models.CharField(max_length=7)),
                ('color_tertiary', models.CharField(max_length=7)),
            ],
        ),
    ]
