# Generated by Django 5.1.1 on 2024-10-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustes',
            name='font_file',
            field=models.FileField(blank=True, null=True, upload_to='fonts/'),
        ),
    ]
