# Generated by Django 5.1.1 on 2024-10-10 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0002_ajustes_font_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ajustes',
            old_name='font_size_large',
            new_name='font_size_paragraph',
        ),
        migrations.RenameField(
            model_name='ajustes',
            old_name='font_size_medium',
            new_name='font_size_subtitle',
        ),
        migrations.RenameField(
            model_name='ajustes',
            old_name='font_size_small',
            new_name='font_size_title',
        ),
    ]
