# Generated by Django 5.1.1 on 2024-11-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0003_rename_font_size_large_ajustes_font_size_paragraph_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_archivo', models.CharField(choices=[('imagen', 'Imagen'), ('documento', 'Documento'), ('audio', 'Audio'), ('video', 'Video'), ('subtitulo', 'Subtítulo')], max_length=50)),
                ('archivo', models.FileField(upload_to='archivos/')),
            ],
        ),
    ]
