# Generated by Django 5.1.1 on 2024-11-20 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0004_archivos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archivos',
            new_name='Archivo',
        ),
        migrations.AlterModelOptions(
            name='archivo',
            options={'verbose_name': 'Archivo', 'verbose_name_plural': 'Archivos'},
        ),
    ]
