# Generated by Django 5.1.1 on 2024-11-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0006_alter_archivo_tipo_de_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='alto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivo',
            name='ancho',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivo',
            name='duracion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivo',
            name='formato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='archivo',
            name='peso',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
