# Generated by Django 5.1.1 on 2024-11-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0007_archivo_alto_archivo_ancho_archivo_duracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
